print("Nhập chuỗi: ", end=' ')
s = str(input())
s = s.upper()
so_lan_A = s.count('A')
so_lan_B = s.count('B')
so_lan_C = s.count('C')
so_lan_D = s.count('D')
print("Số lần xuất hiện của chữ cái A là: %d" % so_lan_A)
print("Số lần xuất hiện của chữ cái B là: %d" % so_lan_B)
print("Số lần xuất hiện của chữ cái C là: %d" % so_lan_C)
print("Số lần xuất hiện của chữ cái D là: %d" % so_lan_D)